spring.application.name=mq-consumer
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.docker.compose.enabled=false
spring.rabbitmq.virtual-host=/

spring.devtools.restart.enabled=false
logging.level.root=INFO
logging.level.org.springframework.amqp=INFO
logging.level.rs.ftn.isa.mqconsumer=INFO
spring.profiles.active=default
